### ISSUE TITLE
"Environment.yml should contain a dictionary" error?

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo-binder#1]
When I try my notebook on pangeo-binder:
[![Binder](http://binder.pangeo.io/badge.svg)](http://binder.pangeo.io/v2/gh/rsignell-usgs/adcirc_cloud/master?filepath=Read_ADCIRC_zarr_s3.ipynb)
I'm getting a build error:
```
dMap'>Waiting for build to start...
Cloning into '/tmp/repo2dockerhvdmfjgu'...
HEAD is now at d860787 Update environment.yml
Error during build: environment.yml should contain a dictionary. Got <class 'ruamel.yaml.comments.CommentedMap'>
```
which is strange, since the `environment.yml` works fine locally.

@jhamman, probably something simple, right?   😸

**Comment by mrocklin** [comment]
I recommend trying this on the normal mybinder.org site and, if the error
persists there, reporting it upstream to the binder folks who may be more
able to respond.

**Comment by jhamman** [comment]
Reported upstream in https://github.com/jupyter/repo2docker/issues/379.

**Comment by rsignell-usgs** [comment]
Yes, my environment is building now and the notebook launches!
