### ISSUE TITLE
issues with gcsfs authentication

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-binder#10]
As reported in https://github.com/pangeo-data/pangeo-example-notebooks/issues/14, I find I can no longer open zarr gcsfs datasets without specifying `token='anon'`.

Could be resolved there (by changing all the notebooks), or here, by changing how gcsfs works.

**Comment by mrocklin** [comment]
cc @martindurant

**Comment by jhamman** [comment]
This seems to have been fixed by fd7286d01db28365c2e0f9dbe61e2e1f4bbef1a6. @rabernat - please close this if it things seem to work for you now.
