### ISSUE TITLE
Drop kube-lego for https

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-binder#127]
I'm trying to stand up a new binderhub on AWS and have been running into errors such as `NET::ERR_CERT_AUTHORITY_INVALID`

@jhamman and @TomAugspurger - I think we can get rid of kube-lego right? See https://github.com/jupyterhub/binderhub/pull/1001  and new binderhub docs for enabling HTTPS https://binderhub.readthedocs.io/en/latest/https.html 

https://github.com/pangeo-data/pangeo-binder/blob/9a4d7d9823dd48302442949c77a8e17b4c582b60/pangeo-binder/values.yaml#L179-L186

`kubectl logs binder-prod-kube-lego-574687f898-gvwpl  -n binder-prod`
```
time="2020-03-25T00:16:11Z" level=info msg="process certificate requests for ingresses" context=kubelego
time="2020-03-25T00:16:11Z" level=info msg="no cert associated with ingress" context=ingress_tls name=jupyterhub namespace=binder-prod
time="2020-03-25T00:16:11Z" level=info msg="requesting certificate for hub.aws-test-binder.pangeo.io" context=ingress_tls name=jupyterhub namespace=binder-prod
time="2020-03-25T00:16:11Z" level=error msg="Error while processing certificate requests: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details." context=kubelego
time="2020-03-25T00:16:11Z" level=error msg="worker: error processing item, requeuing after rate limit: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details." context=kubelego
```

Also the PR that did away with kube-lego on jupyterhub https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1539

**Comment by TomAugspurger** [comment]
I don't know. I'm happy to trust you on this one :)

**Comment by jhamman** [comment]
I don't think the binderhub chart has deprecated kubelego yet: 

https://github.com/jupyterhub/mybinder.org-deploy/blob/7bfe17be11dabd912389fddc7d4ee2c0508bc342/mybinder/values.yaml#L321-L328

and 

https://github.com/jupyterhub/binderhub/blob/b21f341c956f01f4243db227e935d6cf87ce230b/helm-chart/binderhub/values.yaml#L184

May be worth reading over this one: https://github.com/jupyterhub/binderhub/issues/676

**Comment by scottyhq** [comment]
@jhamman - have a look at https://github.com/jupyterhub/mybinder.org-deploy/issues/1148. I'm unable to get a new deployment to work with kube-lego https. Perhaps it is still working for existing deployments.

**Comment by salvis2** [comment]
This has been implemented! Dropped from `staging` in https://github.com/pangeo-data/pangeo-binder/commit/95f5fbab181377f12a32f0f4f02780cde57f8b16#diff-5bfe3ca89def45bb24e8da7ae2c44583412fe127e22160678d38991f98d32423 and `prod` in https://github.com/pangeo-data/pangeo-binder/commit/dd5f4907ed8ab0a015567ab526834802000cbf15#diff-5bfe3ca89def45bb24e8da7ae2c44583412fe127e22160678d38991f98d32423
