### ISSUE TITLE
Migrating away from daskkubernetes service account

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-binder#129]
@jhamman @TomAugspurger - In light of https://github.com/pangeo-data/pangeo-binder/pull/128 As we transition to using dask-gateway, we still need to decide what service account to give dask worker pods and jupyter notebook pods. Right now they get the overly permissive `daskkubernetes` service account. If we take that away they get the `default` service account. 

I'm thinking we should move to a `pangeo` service account for dask workers and jupyter notebooks. That way you can more easily link access to specific cloud resources like s3 buckets - see https://github.com/pangeo-data/pangeo-cloud-federation/issues/485.

Linking those resources to the `default` service account doesn't feel right because so many pods use it.

**Comment by TomAugspurger** [comment]
Agreed that linking those resources to the `default` service account isn't wise.

I don't see any problem with doing this in the base `pangeo-values.yml` that's shared.
