### ISSUE TITLE
Maximum runtime?

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo-binder#13]
I've noticed that occasionally we have jupyter pods that have been around for 6+ hours.  I wonder if we should cap runtime at some limit, perhaps the maximum that we expect for a tutorial?

**Comment by jhamman** [comment]
I've noticed this too. Currently we are "culling" inactive users after 600 seconds. 

https://github.com/pangeo-data/pangeo-binder/blob/94ec01242ac867cdcd9058ed70bd6ad0d51667ad/deploy/binder_config.yml#L45-L47

Obviously, this doesn't seem to be working. I don't know of another way to force user sessions to go away. Is there a setting for a maximum user session duration?

**Comment by mrocklin** [comment]
> Is there a setting for a maximum user session duration?

cc @choldgraf

**Comment by minrk** [comment]
There's a [cull.maxAge](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/a1692479f2a25ddfdbe400a00569c59f58d6ff34/jupyterhub/values.yaml#L287) used to set the maximum age of user pods. Once they exceed this value, they are shutdown regardless of activity.

We use [6 hours](https://github.com/jupyterhub/mybinder.org-deploy/blob/c77c0767ddef603f211a8bc9dfd834330a4083e8/mybinder/values.yaml#L105) on mybinder.org.
