### ISSUE TITLE
AWS build failing

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-data/pangeo-binder#135]
https://app.circleci.com/pipelines/github/pangeo-data/pangeo-binder/136/workflows/6ffd20d5-9965-45bc-b357-bbd263c4756d/jobs/144

```
#!/bin/bash -eo pipefail
aws eks update-cluster-config --name pangeo-binder --resources-vpc-config publicAccessCidrs=${AWS_IP_WHITELIST} > /dev/null



An error occurred (InvalidParameterException) when calling the UpdateClusterConfig operation: Cluster is already at the desired configuration with endpointPrivateAccess: true , endpointPublicAccess: true, and Public Endpoint Restrictions: [*************]


Exited with code exit status 255

CircleCI received exit code 255
```

cc @scottyhq

**Comment by scottyhq** [comment]
Thanks for the heads up. I think with the current setup if two CI runs trigger in quick succession there will be errors with the AWS Authentication. Basically, two Runner IPs are trying to be whitelisted, but the code is only allowing 1 at a time to be registered. The end of the flow always reverts to the original whitelist, so the timing of these commands can cause failures. 

So I'll close this, but let's try to space out commits to staging or prod by at least a couple minutes for the time being.
