### ISSUE TITLE
Setting worker pool taint for dask workers

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-binder#15]
@mrocklin had setup the worker pool for binder.pangeo.io with a taint (`dask-worker: True`). I'm now curious how he did that. From the GKE web interface or via the command line? In either even, it would be good to document how this was done so that when we rebuild the node pools, we can repeat this step.

(Note, the taint is no longer in action as I have redeployed the worker pool this morning).

**Comment by jhamman** [comment]
For reference, I'm setting the user and worker node pools in the following way: 

```
# Core pool
gcloud beta container node-pools create n1-standard-16 \
    --zone=us-central1-b \
    --cluster=binder \
    --machine-type=n1-highmem-32 \
    --preemptible \
    --enable-autoscaling \
    --num-nodes=0 \
    --max-nodes=100 \
    --min-nodes=0 \
    --disk-type=pd-ssd

# standard worker pool
gcloud beta container node-pools create worker-pool \
    --zone=us-central1-b \
    --cluster=binder \
    --machine-type=n1-highmem-32 \
    --preemptible \
    --enable-autoscaling \
    --num-nodes=0 \
    --max-nodes=100 \
    --min-nodes=0 \
    --disk-type=pd-ssd
```

**Comment by mrocklin** [comment]
I didn't set up a taint.  I set up a label.  This encourages worker pods to
go to this node pool, but does not discourage other pods from also going to
this node pool.

I did this when setting up the node pool in the GCP web interface.

**Comment by jhamman** [comment]
Thanks @mrocklin - I tried via the command line without any success using the documented api for this feature: 
```
gcloud beta container node-pools create worker-pool \
    --zone=us-central1-b \
    --cluster=binder \
    --machine-type=n1-highmem-32 \
    --preemptible \
    --enable-autoscaling \
    --num-nodes=0 \
    --max-nodes=100 \
    --min-nodes=0 \
    --disk-type=pd-ssd \ 
    --node-labels=dask-worker=True
```

Unfortunately, this yields an error:
```
ERROR: (gcloud.beta.container.node-pools.create) unrecognized arguments:
Usage: gcloud beta container node-pools create NAME [optional flags]
  optional flags may be  --accelerator | --cluster | --disk-size | --disk-type |
                         --enable-autorepair | --enable-autoscaling |
                         --enable-autoupgrade | --enable-cloud-endpoints |
                         --help | --image-type | --local-ssd-count |
                         --machine-type | --max-nodes | --min-cpu-platform |
                         --min-nodes | --node-labels | --node-taints |
                         --node-version | --num-nodes | --preemptible |
                         --region | --scopes | --service-account | --tags |
                         --workload-metadata-from-node | --zone

For detailed information on this command and its flags, run:
  gcloud beta container node-pools create --help
zsh: command not found: --node-labels=dask-worker=True
```

My attempts to escape or quote the label also seem to have failed. 

I did recreate the node pool with the label via the web interface and things should be working again.

**Comment by guillaumeeb** [comment]
Did you try without the first equal sign?
```
gcloud container clusters create [CLUSTER_NAME] --labels [KEY]=[VALUE]
```

Or maybe updating after creation ?

See https://cloud.google.com/kubernetes-engine/docs/how-to/creating-managing-labels

**Comment by jhamman** [comment]
That didn't work either. Its pretty easy to just do this on the web interface so for now, I'm just going to stick with that. I'm going to close this with the following screen grabs for reference on our current setup:

![image](https://user-images.githubusercontent.com/2443309/47967721-68ae7980-e015-11e8-89cb-1859a38adb01.png)
![image](https://user-images.githubusercontent.com/2443309/47967726-7663ff00-e015-11e8-83fa-51da355fff4b.png)
