### ISSUE TITLE
Update prometheus-operator deployments

### ISSUE THREAD

**Issue by salvis2** [pangeo-data/pangeo-binder#166]
#155 and #158 set up the `prometheus-operator` deployment. 

However, `prometheus-operator` is now [deprecated](https://github.com/helm/charts/tree/master/stable/prometheus-operator#%EF%B8%8F--deprecated). The proper Helm chart is now [`kube-prometheus-stack`](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack). This should be changed. Hopefully it's as simple as changing the repo / chart names. There is also a new `CRD`: `probes.monitoring.coreos.com`.

Additionally, there will have to be a little work to enable HTTPS for the Grafana endpoint, see discussion here: https://github.com/pangeo-data/pangeo-binder/pull/155#issuecomment-670199494. 

If we want to make setup easier, we should configure Grafana to use its own LoadBalancer. This will cost money. If we want to avoid that, we will need to figure out how to set up another `Issuer` that uses the [DNS01 Solver](https://cert-manager.io/docs/configuration/acme/dns01/) (as opposed to the [HTTP01 Ingress Provider](https://cert-manager.io/docs/configuration/acme/http01/), which we use in binderhubs, ex. [AWS staging issuer](https://github.com/pangeo-data/pangeo-binder/blob/staging/k8s-aws/binderhub-issuer-staging.yaml#L17) and [GCP staging issuer](https://github.com/pangeo-data/pangeo-binder/blob/staging/deploy/binderhub-issuer-staging.yaml#L17)).

**Comment by salvis2** [comment]
Cool, the `kube-prometheus-stack` readme has a section on [migrating from `prometheus-operator`](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#migrating-from-stableprometheus-operator-chart).

Looks like the `prometheus-operator` chart got taken out recently: https://github.com/pangeo-data/pangeo-binder/commit/95f5fbab181377f12a32f0f4f02780cde57f8b16#diff-06e805e5c3973f9c240e7dcb407c3d58L18-L20. I think this was an accident @TomAugspurger , but hey, it gives me a clean slate for this.

I'm deleting all the `CRD`s.

I'm having some `CRD` installation problems. If I just put the new helm chart into the dependencies of `pangeo-binder` and try the `helm install` command, I get several lines like

```
unable to recognize "": no matches for kind "Alertmanager" in version "monitoring.coreos.com/v1"
```

If I try to install the `CRD`s as listed in the [readme](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#helm-fails-to-create-crds), I get errors such as

```
error: unable to recognize "<filepath-omitted>": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
```

The versions listed there are for `prometheus-operator` v0.42. We used to be using v0.38, which have `apiVersion: apiextensions.k8s.io/v1beta1`. There is also another resource listed, `probes.monitoring.coreos.com`, but this resource isn't present in v0.38, and the other `CRD`s do not have a cooperative `apiVersion` after v0.38.

There are also `CRD`s listed in the [`crds/` folder](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/crds) of the repo, so I'm guessing that they haven't gotten around to putting those in the readme. Trying to install these charts (from the `raw.githubusercontent` links) shows errors:

```
no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
```

as with the v0.42 `prometheus-operator` `CRD`s.

This latest version of `kube-prometheus-stack` is v10.0.1, which was released 2 hours ago. I'll take a break on this and see if the helm chart and it's instructions become more up-to-date later.

A final thought: `kubectl version` says my local machine is on v1.17.4 but the AWS `pangeo-binder` is on v1.15.11. I'm wondering if the `apiVersions` aren't working because of that.

**Comment by salvis2** [comment]
@TomAugspurger we don't need to make a decision on this quickly (JupyterCon and ADSA 2020) will keep me busy this week), but if this isn't resolved next week, I'm thinking of just going back to Prometheus and Grafana as individual charts. I'm more confident that this will work at a basic level (especially since it's easier to pin to older versions that we know work). Let me know if you have any thoughts on anything here.

**Comment by TomAugspurger** [comment]
+100 to simplification. I didn't realize that prometheus-operator was so complicated when I picked it.

**Comment by salvis2** [comment]
Checked the `kube-prometheus-stack` repo again today, no significant changes, and the readme didn't have different instructions, so I went and manually tried to deploy Prometheus and Grafana on the AWS staging binder.

@TomAugspurger I've got a configuration working for the two individual charts. I see you have an open PR, should I wait on that or just open up my PR and let you take a look?

**Comment by TomAugspurger** [comment]
Go ahead whenever!
