### ISSUE TITLE
Additional Details on ReadME?

### ISSUE THREAD

**Issue by jzf2101** [pangeo-data/pangeo-binder#17]
Installation details are few

**Comment by jhamman** [comment]
Thanks @jzf2101 - 

So we currently just say:

```bash
cd helm-chart
helm upgrade binder --install pangeo-binder --namespace=pangeo-binder --version=v0.1.0 -f ../deploy/binder_config.yml -f ../deploy/mybinder_secret.yaml
```

What else is needed here? Looking at the Zero to BinderHub docs (outline below), we only differ in step 3.4. Is it worth publishing the pangeo-binder helm chart? I have just been installing it from a local copy of this repository. 

1. Create your cloud resources
1.1. Setting up Kubernetes on Google Cloud
1.2. Install Helm
2. Set up the container registry
2.1. Set up Google Container Registry
2.2. Set up Docker Hub registry
2.3. Next step
3. Set up BinderHub
3.1. Preparing to install
3.2. Create secret.yaml file
3.3. Create config.yaml
3.4. **Install BinderHub**
3.5. Connect BinderHub and JupyterHub
3.6. Try out your BinderHub Deployment
3.7. Increase your GitHub API limit
4. Tear down your Binder deployment
4.1. Contracting the size of your cluster
4.2. Deleting the cluster

**Comment by jzf2101** [comment]
that's fine I just wanted something that contextualizes the installation instructions.

**Comment by jhamman** [comment]
I'll write this up in the readme as I assume it will be of use to others.

Are you interested in deploying this chart instead of the binderhub chart?

**Comment by jzf2101** [comment]
you mean am I planning on deploying this now? not immediately at least.

**Comment by jhamman** [comment]
closed via https://github.com/pangeo-data/pangeo-binder/commit/7afde6dff172240fcaf1bdf25158f2a9becad612

**Comment by jhamman** [comment]
@jzf2101 - I've added some context to the setup instructions in the readme. Hopefully this helps.
