### ISSUE TITLE
Dask-Gateway Workers in CrashLoopBackOff

### ISSUE THREAD

**Issue by salvis2** [pangeo-data/pangeo-binder#173]
@TomAugspurger I went to check out the binder cluster for Prometheus / Grafana stuff and found a bunch of dask-gateway workers in `CrashLoopBackOff`. Logs from one of them say `error: unrecognized arguments: --dashboard-address :8787`. Seems familiar!

**Comment by scottyhq** [comment]
@salvis2 that's going to happen if people run a container with dask-gateway<0.8 if I understand correctly. It's come up in the past to have some sort of user-facing warning about this. i think currently when someone tries to create a cluster with an old dask-gateway it just hangs... 

see https://github.com/pangeo-data/pangeo-binder/issues/144

**Comment by salvis2** [comment]
I remember hitting that when trying to get the multicloud demo working. Wasn't sure if it was a user issue or a binder issue so I brought this up.
