### ISSUE TITLE
Can't set environment variables for dask-gateway

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-binder#175]
We can do this on Pangeo Hubs, but not Binder currently. 

Seems like it's just a straightforward copy of the following
https://github.com/pangeo-data/pangeo-cloud-federation/blob/a2d6c9a31a7a08c27275c4df6c779aba7c2c4c65/pangeo-deploy/values.yaml#L124-L131

to values.yaml in this repo
https://github.com/pangeo-data/pangeo-binder/blob/6b4a75210042a349a91ba17bea91a2e4e64afed7/pangeo-binder/values.yaml#L240

@TomAugspurger - am I missing anything? I think some Pangeo Gallery examples will likely depend on this

**Comment by TomAugspurger** [comment]
Yep I think that's all there is to it.

Just need to provide the Mapping option and then make sure that it's in the dict returned https://github.com/pangeo-data/pangeo-cloud-federation/pull/762/files.
