### ISSUE TITLE
can't launch dask gateway cluster if image has dask-gateway>=0.9

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-binder#185]
Just noting along with current pangeo hub infrastructure (https://github.com/pangeo-data/pangeo-cloud-federation/issues/859), we're currently unable to launch clusters if dask-gateway>=0.9 is installed in an image (so any pangeo-notebook image after 2020.11.06). For example: 

|  [![badge](https://img.shields.io/static/v1.svg?logo=Jupyter&label=PangeoBinder&message=2020.11.06&color=orange)](https://aws-uswest2-binder.pangeo.io/v2/gh/pangeo-data/notebook-binder/2020.11.06?urlpath=lab) | [![badge](https://img.shields.io/static/v1.svg?logo=Jupyter&label=PangeoBinder&message=2020.11.06&color=blue)](https://binder.pangeo.io/v2/gh/pangeo-data/notebook-binder/2020.11.06?urlpath=lab)  | [2020.11.06](https://github.com/pangeo-data/pangeo-docker-images/blob/2020.11.06/pangeo-notebook/packages.txt) |

https://github.com/pangeo-data/pangeo-binder/pull/184 should fix things

**Comment by roxyboy** [comment]
I think I'm having the same issue by configuring the Pangeo Binderhub with `pangeo-notebook==2020.08.31`. Is a temporary fix to set `dask-gateway<0.9`?

**Comment by scottyhq** [comment]
this issue was closed by https://github.com/pangeo-data/pangeo-binder/pull/184 

@roxyboy you need dask-gateway>=0.9 in your image on pangeo binderhubs. So and image tag after 2020.11.06 as you can see here https://github.com/pangeo-data/pangeo-docker-images#dask-gateway-compatibility

**Comment by rabernat** [comment]
My hope is that the [default binder](https://github.com/pangeo-gallery/default-binder) can help us avoid issues like this.

Has either of you considered using the default binder image for your binder?

**Comment by roxyboy** [comment]
> My hope is that the [default binder](https://github.com/pangeo-gallery/default-binder) can help us avoid issues like this.
> 
> Has either of you considered using the default binder image for your binder?

I tried using the Pangeo-Binder cookiecutter initially to configure my Binderhub but the template I got seemed to be quite outdated and couldn't make it work...

**Comment by TomAugspurger** [comment]
I didn't realize we still had https://pangeo-binder.readthedocs.io/en/prod/#using-the-pangeo-binder-cookiecutter in the docs.

I would also recommend building off  default-binder & nbgitpuller, as documented at https://pangeo-binder.readthedocs.io/en/prod/#using-pangeo-s-binder

**Comment by rabernat** [comment]
Ok, so we have a communications problem here. Our websites / docs are out of date from our current best practices.

**Comment by roxyboy** [comment]
It's probably a patch solution but I seem to have got the dask workers in Binderhub to work with
```
pangeo-notebook=2020.11.06
dask-gateway>=0.9
```
in my `environment.yml` file for binder following @scottyhq 's advice.
