### ISSUE TITLE
Launching server fails

### ISSUE THREAD

**Issue by lsterzinger** [pangeo-data/pangeo-binder#193]
Recently, when trying to launch a notebook on https://binder.pangeo.io, the image builds/uploads fine but I keep erroring on launch. I don't know where/if there is additional log info so I can't tell anything more than what the error message below shows:
![image](https://user-images.githubusercontent.com/6716906/135663712-6fe6cfdb-cb09-4365-8ce0-58bbeac6f8aa.png)

For reference the notebook I'm trying to launch is: https://binder.pangeo.io/v2/gh/lsterzinger/maptimedavis-fsspec/HEAD

**Comment by rabernat** [comment]
Possibly related to #192

**Comment by lsterzinger** [comment]
Possibly. I have not encountered any issues generating an image, only launching the server

**Comment by lsterzinger** [comment]
Though updating repo2docker might help in this instance, as @choldgraf mentioned in #192

**Comment by scottyhq** [comment]
@lsterzinger unfortunately all logs are not exposed to users, if i try and launch your repository I notice the following: 
```
      File "/srv/conda/envs/notebook/lib/python3.8/site-packages/jupyterlab/__init__.py", line 7, in <module>
        from .labapp import LabApp
      File "/srv/conda/envs/notebook/lib/python3.8/site-packages/jupyterlab/labapp.py", line 15, in <module>
        from jupyter_server.serverapp import flags
      File "/srv/conda/envs/notebook/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 52, in <module>
        raise ImportError(_i18n("The Jupyter Server requires tornado >=%s.%s.%s") % MIN_TORNADO) from e
    ImportError: The Jupyter Server requires tornado >=6.1.0
```

Looking at your repository configuration I don't see a `Dockerfile`, we should document this better here https://github.com/pangeo-data/pangeo-docker-images#how-to-use-the-base-image-with-a-pangeo-binder, but if you want a fully custom environment that works on the pangeo binders (with dask gateway), I recommend following the [pangeo binder template](https://github.com/pangeo-data/pangeo-binder-template). At a minimum you'll want

1. a [`Dockerfile`](https://github.com/pangeo-data/pangeo-binder-template/blob/2769e730b9ae9cafdce58e6ab3d88e239b6d098a/binder/Dockerfile#L1) that points to a specific pin of the pangeo base image (`FROM pangeo/base-image:2021.09.21`)
2. you then need to make sure you have the `pangeo-notebook` metapackage in your [environment.yml](https://github.com/pangeo-data/pangeo-binder-template/blob/2769e730b9ae9cafdce58e6ab3d88e239b6d098a/binder/Dockerfile#L1)


NOTE that if you just want an additional package or two that is not in the `pangeo-notebook` environment you can simply modify the Dockerfile as is done here https://github.com/rabernat/pangeo-interactive-talks/blob/binder/binder/Dockerfile 

Hope that helps explain things a bit. cc @scollis

**Comment by lsterzinger** [comment]
Using the pangeo binder template fixed my issue and I'm able build/deploy on https://binder.pangeo.io error free now. Thanks @scottyhq

**Comment by acocac** [comment]
@scottyhq, I've just found the same launch error even with the template,
repo: [https://github.com/acocac/pangeo-binder-template](https://github.com/acocac/pangeo-binder-template
)

**Comment by rabernat** [comment]
The Pangeo Binder has been shut down due to crypto mining - see https://github.com/pangeo-data/pangeo-binder/issues/195

@acocac - can you do what you need to do on mybinder.org?

**Comment by scollis** [comment]
This is why we can’t have nice things

 

--

Dr Scott Collis  (He/Him)

Atmospheric Scientist | Radar Instrument Translator | Senior Fellow | Editor

Argonne National Laboratory | ARM User Facility | NAISE | AMS AI4ES

I triage my emails, if you need immediate attention please text my cell: 630 235 8025

 

Blog  | Twitter | Media (WIP)

 

 

 

 

From: Ryan Abernathey ***@***.***>
Reply-To: pangeo-data/pangeo-binder ***@***.***>
Date: Wednesday, December 8, 2021 at 12:13 PM
To: pangeo-data/pangeo-binder ***@***.***>
Cc: Scott ***@***.***>, Mention ***@***.***>
Subject: Re: [pangeo-data/pangeo-binder] Launching server fails (#193)

 

The Pangeo Binder has been shut down due to crypto mining - see #195

@acocac - can you do what you need to do on mybinder.org?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by acocac** [comment]
@rabernat sorry I just saw the issue of the crypto mining 😭  Apart from `dask`, my main reason of using Pangeo binder is a larger memory (8MB) than the regular mybinder.org (2MB). I'm positive the improvement led by 2i2c engineers will bring a faster binder with more stability and security 💪 🌎

**Comment by lsterzinger** [comment]
@acocac I ran into the same issue w/ needing more memory than what MyBinder allocates. When I couldn't get the pangeo binder working, I looked into Google Colab (https://colab.research.google.com/) as a slightly inconvenient but doable alternative.

**Comment by acocac** [comment]
@lsterzinger, thanks for the suggestion! I'm temporarily exploring [GESIS](https://notebooks.gesis.org/), not optimal for `dask` as the Pangeo binder, but at least fits the memory requirement. I'm strongly convinced we'll have a fast and robust Pangeo binder after the migration to 2i2c 🤞 💨 .
