### ISSUE TITLE
Use binder appendix to inject dask/pangeo configs and dependencies

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-binder#20]
Using the repo2docker/binder appendix, we could:

- populate all user images with some default dask configurations (put in /etc/dask)
- make sure certain packages are installed (maybe dask/distributed/dask-kubernetes)
- install any extensions we think everyone may want

example application: https://github.com/jupyterhub/binderhub/tree/b32ad4425be3319f7a2c59cf8253e979512b955d/examples/appendix

**Comment by yuvipanda** [comment]
Is this still something y'all wanna do?

**Comment by jhamman** [comment]
@yuvipanda - maybe. I know how to do it. I think the main pain point at the moment is figuring out how to enforce that users put their dask workers in the right node pool (preemptible). I think we can do that without the appendix so I'm pushing in that direction right now.
