### ISSUE TITLE
Binder is broken (certificate issue?)

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-binder#23]
When I go to https://binder.pangeo.io, i get `NET::ERR_CERT_AUTHORITY_INVALID`.

@willirath and @jacobtomlinson also reported problems earlier today.

It's a bit hard to debug for me.

**Comment by willirath** [comment]
It uses a cert called "Kubernetes Ingress Controller Fake Certificate" [There seem to be many Github issues that may provide hints.](https://github.com/search?q=%22Kubernetes+Ingress+Controller+Fake+Certificate%22&type=Issues)

**Comment by jacobtomlinson** [comment]
We get this on our cluster when Cert Manager is failing to issue Lets Encrypt certs. Not sure what you are using for SSL cert generation but it could be this.

**Comment by jhamman** [comment]
This is almost fixed. Just waiting on some help from someone who knows anything about https. Current PR is #27.

**Comment by jhamman** [comment]
Just jotting down what I've tried (without success just yet):

- vanilla redeploy (see #27)
- rename lego secret (see 1b9333f988ed6444e1e632f33c25575a4f1cc95d)
- kill kubelego pod (to force recreation)
- redeploy w/ force recreate pods

**Comment by rabernat** [comment]
You're a hero Joe!

**Comment by mrocklin** [comment]
Hooray Joe!

**Comment by jhamman** [comment]
Things should be working now for both https://binder.pangeo.io/ and https://staging.binder.pangeo.io/. If you get a cert error, you may just need to wait a bit longer as some dns entries may still be propagating.

**Comment by scottyhq** [comment]
just ran into this on the pangeo aws binder. Just running `kubectl delete pods -n binder-staging binder-staging-kube-lego-84c9c589cf-9bk7z` and waiting a few minutes fixed the problem
