### ISSUE TITLE
Loosing connection to my binder notebook

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/pangeo-binder#37]
Hi everyone,

Recently when preparing a Pangeo tutorial, I've experience some disconnection from my Binder launched notebook. I add to restart the whole binder notebook, loosing current notebooks state.

I'm not sure what is causing this, this just happened at around 9 UTC.

**Comment by guillaumeeb** [comment]
This has append a few time during my tutorial today for some attendees.

Could this be that notebooks are launched on preemptible VM pools? Any other thoughts?

**Comment by rabernat** [comment]
The jupyter nodepool is definitely preemptible.

**Comment by jcrist** [comment]
I'm seeing this as well while just prepping my materials for tomorrow. Seems to correlate with doing work on the cluster, but it's the notebook instance that's getting killed not the workers.

**Comment by guillaumeeb** [comment]
Would this be complicated/realistic/not too expensive to use a non preemptible pool for user notebooks?

**Comment by rabernat** [comment]
@jhamman - thoughts on making the `jupyter-pool` non-preemptible?

Anyone - do you know what to look for in the logs in order to verify that it was preemption (rather than some other error) causing this behavior?

**Comment by jhamman** [comment]
It would be great if we had more fine grained telemetry to help diagnose these things after the fact. See #5 and https://github.com/jupyterhub/mybinder.org-deploy/issues/911. 

> The jupyter nodepool is definitely preemptible.

This is true but I believe by accident. We recently rebuilt the cluster and this change was not intentional.

**Comment by jhamman** [comment]
FYI, I've moved the notebook pool over to standard instances (not preemptible). 

Just to remind everyone, these lines here will make sure you dask-workers land in the preemptible pool: 

https://github.com/pangeo-data/pangeo-example-notebooks/blob/9b4e888ad28836c8321a2eb2e7b0f3a04dcd64d8/.dask/config.yaml#L21-L22
