### ISSUE TITLE
user-pool not scaling down completely

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-binder#57]
![image](https://user-images.githubusercontent.com/2443309/58383996-859aa200-7f91-11e9-8bfc-c4526c64ceb8.png)

Following the recent cluster updates and associated scheduling changes (affinity/taints/tolerations), most things in the cluster seem to be working really well. One issue still seems to present where the user-pool doesn't scale to size zero when not in use. Here's an example from a few minutes ago where a node hasn't scaled down despite hours of inactivity.

```shell
$ kubectl get pods --all-namespaces --output wide | grep user-pool
kube-system   fluentd-gcp-v3.1.1-p4g8t                                    2/2     Running   0          2d7h    10.128.0.64    gke-binder-user-pool-45fded5e-qlnh   <none>
kube-system   kube-proxy-gke-binder-user-pool-45fded5e-qlnh               1/1     Running   0          2d7h    10.128.0.64    gke-binder-user-pool-45fded5e-qlnh   <none>
kube-system   stackdriver-metadata-agent-cluster-level-8449cbd999-p667l   1/1     Running   1          2d7h    10.49.224.3    gke-binder-user-pool-45fded5e-qlnh   <none>
prod          prod-dind-4s2m7                                             1/1     Running   0          42h     10.49.224.29   gke-binder-user-pool-45fded5e-qlnh   <none>
prod          prod-image-cleaner-lqh4z                                    1/1     Running   0          42h     10.49.224.30   gke-binder-user-pool-45fded5e-qlnh   <none>
staging       staging-dind-dqr4h                                          1/1     Running   0          42h     10.49.224.26   gke-binder-user-pool-45fded5e-qlnh   <none>
staging       staging-image-cleaner-c5dl9                                 1/1     Running   0          42h     10.49.224.27   gke-binder-user-pool-45fded5e-qlnh   <none>
```

So there are three system pods, and dind/cleaner daemonset pods for each namespace deployment. My understanding is that none of these should keep the node alive in the absence of a notebook/build pod. @consideRatio, am I misinterpreting the scheduling behavior?

https://github.com/pangeo-data/pangeo-binder/blob/998f046c43b006f6a918cf1c1e5cf60c7d04a997/helm-chart/pangeo-binder/values.yaml#L36-L46

**Comment by consideRatio** [comment]
@jhamman hmmmm hmmmm, I'm somewhat new to BinderHub world, and dind especially. They are daemonsets right? I don't understand why this does not scale down then.

I would inspect the cluster autoscaler's status:

```sh
# look under the NodeGroups title for the node-pool of relevance
# does it identify candidates for example?
kubectl get cm -n kube-system cluster-autoscaler-status -o yaml
```

```
    NodeGroups:
      Name:        https://content.googleapis.com/compute/v1/projects/ds-platform/zones/europe-west4-a/instanceGroups/gke-ds-platform-users-e99bd23e-grp
      Health:      Healthy (ready=1 unready=0 notStarted=0 longNotStarted=0 registered=1 longUnregistered=0 cloudProviderTarget=1 (minSize=0, maxSize=3))
                   LastProbeTime:      2019-05-26 16:06:29.451821679 +0000 UTC m=+24264.965654891
                   LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC
      ScaleUp:     NoActivity (ready=1 cloudProviderTarget=1)
                   LastProbeTime:      2019-05-26 16:06:29.451821679 +0000 UTC m=+24264.965654891
                   LastTransitionTime: 2019-05-26 15:47:49.0528279 +0000 UTC m=+23144.566661089
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2019-05-26 16:06:29.451821679 +0000 UTC m=+24264.965654891
                   LastTransitionTime: 2019-05-26 15:47:49.0528279 +0000 UTC m=+23144.566661089
```

---

I'd also learn more about the image cleaner and the dind pods:
- are they from daemonsets?
- Do they have a PDB targeting them?
- Do they have a cluster-autoscaler related annotations on them saying something like system-critical or safe-to-evict (this last annotation is deprecated I think).

**Comment by jhamman** [comment]
For some reason, the cloudProviderTarget is 1 node in this state: 

```
apiVersion: v1
data:
  status: |+
    Cluster-autoscaler status at 2019-05-26 21:58:05.063879692 +0000 UTC:
    Cluster-wide:
      Health:      Healthy (ready=4 unready=0 notStarted=0 longNotStarted=0 registered=4 longUnregistered=0)
                   LastProbeTime:      2019-05-26 21:58:04.287003384 +0000 UTC m=+862953.793784676
                   LastTransitionTime: 2019-05-16 22:15:58.534748738 +0000 UTC m=+28.041530042
      ScaleUp:     NoActivity (ready=4 registered=4)
                   LastProbeTime:      2019-05-26 21:58:04.287003384 +0000 UTC m=+862953.793784676
                   LastTransitionTime: 2019-05-26 04:47:45.767323699 +0000 UTC m=+801135.274104985
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2019-05-26 21:58:04.287003384 +0000 UTC m=+862953.793784676
                   LastTransitionTime: 2019-05-26 05:13:13.608632799 +0000 UTC m=+802663.115414109

    NodeGroups:
      Name:        https://content.googleapis.com/compute/v1/projects/pangeo-181919/zones/us-central1-b/instanceGroups/gke-binder-user-pool-45fded5e-grp
      Health:      Healthy (ready=1 unready=0 notStarted=0 longNotStarted=0 registered=1 longUnregistered=0 cloudProviderTarget=1 (minSize=0, maxSize=25))
                   LastProbeTime:      2019-05-26 21:58:04.287003384 +0000 UTC m=+862953.793784676
                   LastTransitionTime: 0001-01-01 00:00:00 +0000 UTC
      ScaleUp:     NoActivity (ready=1 cloudProviderTarget=1)
                   LastProbeTime:      2019-05-26 21:58:04.287003384 +0000 UTC m=+862953.793784676
                   LastTransitionTime: 2019-05-24 09:16:46.00873405 +0000 UTC m=+644475.515515363
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2019-05-26 21:58:04.287003384 +0000 UTC m=+862953.793784676
                   LastTransitionTime: 2019-05-24 09:47:19.168821679 +0000 UTC m=+646308.675602967
```

> are they from daemonsets?

AFAICT, both the [image-cleaner](https://github.com/jupyterhub/binderhub/blob/master/helm-chart/binderhub/templates/image-cleaner.yaml#L4) and [dind](https://github.com/jupyterhub/binderhub/blob/master/helm-chart/binderhub/templates/dind/daemonset.yaml#L3) pods are daemonsets.

> Do they have a PDB targeting them?

~How would I check this? Googling...~

I don't think so. 

```
NAMESPACE     NAME                                    MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
kube-system   heapster-pdb                            N/A             1                 1                     233d
kube-system   metrics-server-pdb                      N/A             1                 1                     233d
kube-system   tiller-deploy-pdb                       N/A             1                 1                     233d
prod          binderhub                               1               N/A               0                     76d
prod          hub                                     1               N/A               0                     76d
prod          prod-nginx-ingress-controller           1               N/A               1                     76d
prod          prod-nginx-ingress-default-backend      0               N/A               1                     76d
prod          proxy                                   1               N/A               0                     76d
prod          user-scheduler                          1               N/A               1                     76d
staging       binderhub                               1               N/A               0                     3d1h
staging       hub                                     1               N/A               0                     3d1h
staging       proxy                                   1               N/A               0                     3d1h
staging       staging-nginx-ingress-controller        1               N/A               1                     3d1h
staging       staging-nginx-ingress-default-backend   0               N/A               1                     3d1h
staging       user-scheduler                          1               N/A               0                     3d1h
```

> Do they have a cluster-autoscaler related annotations on them saying something like system-critical or safe-to-evict (this last annotation is deprecated I think).

~Same. Googling...~

I don't think so. 

dind & image cleaner:
```
Annotations:        <none>
```

**Comment by jhamman** [comment]
Ah, but the following kube-system pods do have this annotation:

```
Annotations:        scheduler.alpha.kubernetes.io/critical-pod:
```

- fluentd-gcp-v3.1.1
- kube-proxy-gke

**Comment by consideRatio** [comment]
Hmmm but I think these don't block scale down for me... Hmmmm I recall there was a way to read the cluster-autoscaler binaries logs... 

I found:
- https://cloud.google.com/compute/docs/autoscaler/viewing-autoscaler-logs
- https://cloud.google.com/compute/docs/autoscaler/managing-autoscalers#update_an_autoscaler
- https://cloud.google.com/compute/docs/autoscaler/understanding-autoscaler-decisions

Oh autoscaling is off but this is the wrong kind of autoscaling... this is not kubernetes based autoscaling... **WOOPS! Sorry for the distraction. This was irrelevant as the k8s based autoscaler is another abstraction layer higer than this.**

![image](https://user-images.githubusercontent.com/3837114/58388025-0d77bf00-8019-11e9-94e5-36c430a5c71f.png)


![image](https://user-images.githubusercontent.com/3837114/58387987-89bdd280-8018-11e9-81ff-742b790ae160.png)

**Comment by consideRatio** [comment]
This is relevant, kinda what I tried writing up from memory before:
https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler#scheduling-and-disruption

**Comment by consideRatio** [comment]
Regarding the system critical pods, hmmm...

They are kube-system pods that are run on the node by default though... Otherwise they could block by being

> Kube-system pods that:
>     - are not run on the node by default, *

**Comment by consideRatio** [comment]
I don't get this either. I wonder if it relates to having a lot of unschedulable dask-jovyan pods around for some reason... Hmmm

**Comment by consideRatio** [comment]
https://github.com/jupyterhub/mybinder.org-deploy/issues/901

**Comment by jhamman** [comment]
The api server logs are attached. 
[kube-apiserver.log.zip](https://github.com/pangeo-data/pangeo-binder/files/3221559/kube-apiserver.log.zip)

I'm starting to wonder if the presence of daemonsets from two namespaces (prod and staging) are confusing the scheduler here. I say this because mybinder.org-deploy uses two separate clusters for its prod and staging deployments. I wonder if this is why? Maybe @betatim or @yuvipanda can comment.

**Comment by yuvipanda** [comment]
MyBinder.org runs on two clusters because I was young and idealistic. It might be related to this issue, but no idea!

**Comment by jhamman** [comment]
In a moment of desperation, I tore the user-pool down and rebuilt it from scratch. Lo and behold, the user-pool scaled up and back down to zero nodes without incident. The `stackdriver-metadata-agent-cluster-level` pod never came up in the new node-pool so I'm wondering (not sure) if that was the offending pod. In any event, I think I'm going to close this since we seem to be operating as expected now.

Thanks @consideRatio and @yuvipanda for the input.

**Comment by yuvipanda** [comment]
Working with the cloud is 1% inspiration, 49% perspiration and 50% desperation so I approve of this solution.

**Comment by yuvipanda** [comment]
Something I often do to try debug these is to cordon the node, ssh in and just restart the node. This always moves critical pods to other nodes without you having to figure out which ones they are.

**Comment by consideRatio** [comment]
Oh I wonder why that pod were allowed to live on our tainted node without being evictable, sounds wierd
