### ISSUE TITLE
Failed to start server first time image is loaded

### ISSUE THREAD

**Issue by djhoese** [pangeo-data/pangeo-binder#63]
I've noticed that when launching my repository it finds an image, but fails to start the server one time, then succeeds the next attempt.

My tutorial repository is here: https://github.com/pytroll/tutorial-satpy-half-day

![image](https://user-images.githubusercontent.com/1828519/60926655-d843cb00-a26c-11e9-86eb-0f0b6548e25f.png)

**Comment by djhoese** [comment]
@jhamman and I sat down and looked at this yesterday. This was my fault. I had tried to save users from having to download sample data by including it in the image, but this was making it too difficult/large for binder to download and use. I then tried putting the download in `start` but this ended up taking too long and still making binder timeout. I am now trying backgrounding the download script while starting the jupyter lab server and that seems to work well enough. In the future when NetCDF files can be loaded directly from google cloud this won't be an issue since that's what most of my example data is (GOES-16 ABI data on GCS).

Thanks for the help.

**Comment by rabernat** [comment]
Why don't you try putting your data on the cloud in zarr format? That works today.

**Comment by djhoese** [comment]
Mainly time.

1. The readers in Satpy are meant to read the native format produced by the data producer. For ABI that is NetCDF4 files. For VIIRS that is HDF5. It wouldn't be hard to make it accept zarr files but would be a special case and would be a new custom format that wasn't created by the provider.
2. Is there free cloud storage I can use?

**Comment by rabernat** [comment]
Ok I was confused about how your library worked, sorry. I thought you accepted xarray datasets as inputs.

As for 2,
- all cloud providers give a free trial allocation
- you can write a proposal to get bigger credits for free (O($10,000))
- you are of course always welcome to use Pangeo cloud resources
