### ISSUE TITLE
This R-based notebook demo repo works on mybinder.org, but not on pangeo.binder.io

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/pangeo-binder#72]
This [R demo repo using Dockerfile](https://github.com/rerickson-usgs/lamprey_pangeo) works on `mybinder.org`, but fails to launch on `binder.pangeo.io` (and also fails to launch on `aws-uswest2-binder.pangeo.io`).

It builds without errors, but then after three launch attempts, it fails with a "Internal Server Error":
![2019-09-04_14-41-11](https://user-images.githubusercontent.com/1872600/64281886-2817d900-cf22-11e9-8548-35f6ff609b30.png)

**Comment by rsignell-usgs** [comment]
@jhamman do you see anything helpful in the logs?

**Comment by jhamman** [comment]
mybinder.org and binder.pangeo.io are almost identical deployments. One difference that may come into play here is that we default to using jupyterlab. Can you confirm that the docker image has jupyterlab installed?

I'm also curious about the larger goal here. Why not just use mybinder.org? Do you have some way of harnessing Pangeo's dask-kubernetes integration from R?

**Comment by rsignell-usgs** [comment]
@jhamman, yes, we are not using dask clusters here, so we could just use mybinder.org, but this is for a demo promoting Pangeo for use other than big data, so we wanted to say that we were using a Pangeo binder (being controlled by the Pangeo community).   

Thanks for the tip on checking on whether Jupyterlab is installed.  @rerickson-usgs and I will check that out and report back.  Thanks!

**Comment by raerickson** [comment]
@jhamman I am using the `rocker/binder:latest` Docker image as my base. I don't think it has Jupyterlab installed. I tried adding a Jupyter lab install command to my dockerfile, but cannot get it to work.

I'm not tied to this specific docker image, but need one where I can install packages. (I tried using the `install.R` option and couldn't get that to work). Can you point me towards a working R example on Pangeo? I would be happy to adapt to the example's style.

@rsignell-usgs any other thoughts?

**Comment by rsignell-usgs** [comment]
@rerickson-usgs , looks like lack of jupyterlab is the issue.  I built a container `lamprey` using your Dockerfile and compared it to pangeo/notebook:
```
docker run -it pangeo/pangeo-notebook /bin/bash
root@e3ceb2df1e7c:~# pip list | grep jupyter
jupyter-client         5.3.1
jupyter-console        6.0.0
jupyter-core           4.4.0
jupyter-server-proxy   1.1.0
jupyterhub             1.0.0
jupyterlab             1.0.9
jupyterlab-server      1.0.6

docker run -it lamprey /bin/bash
rstudio@b1e8a5834654:~$ pip list | grep jupyter
jupyter-client (5.3.1)
jupyter-core (4.5.0)
jupyter-rsession-proxy (1.0b6)
jupyter-server-proxy (1.1.0)
```

**Comment by raerickson** [comment]
@jhamman and @rsignell-usgs  I've figured out that I need to only use the `environment.yml` file to change R (i.e., do not use a `dockerfile`, do not use  `runtime.txt`, do not use `install.txt`). 

I am unable to close this issue, but it may be closed now

**Comment by jhamman** [comment]
Glad to hear it @rerickson-usgs! Happy bindering.

**Comment by rsignell-usgs** [comment]
As @rerickson-usgs said, it just needed [the R-stuff added to the environment.yml](https://github.com/rerickson-usgs/lamprey_pangeo/blob/master/environment.yml) file
