### ISSUE TITLE
Problem downloading notebook from JupyterLab on pangeo binder

### ISSUE THREAD

**Issue by cgentemann** [pangeo-data/pangeo-binder#80]
@marisolgr and I are showing a jupyter notebook at the PICES meeting on 10/24 (Thursday). We would like to show it using the pangeo binder for a number of reasons. When I run the image, it opens up a Jupyter Lab environment, with the example we want to show, which creates some figures and data files. Everything runs, no problem, but we are getting an error when trying to download any file. I think it may have something to do with this: https://github.com/jupyter/notebook/issues/4541 1. To download a file I just right-click on it and select ‘download’. I then get a Jupyter error ‘Blocking request from unknown origin’

Here is a link to the pangeo binder image:
https://binder.pangeo.io/v2/gh/python4oceanography/PICES-tools/master 1

(I can download if I create the image using mybinder, but I’d rather use pangeo)

(Posted here at request of @rabernat)
Any help appreciated. Thanks, Chelle

**Comment by rabernat** [comment]
The recommended fix in jupyter/notebook#4541 (until a new release) was

>  adding `proxy_set_header Host $host;` to my nginx conf

Not sure how to implement this within our binder, but I bet someone does.

**Comment by rabernat** [comment]
@cgentemann - does your demo need Pangeo-binder special features (like dask_kubernetes)?

**Comment by cgentemann** [comment]
No, we aren't using dask_kubernetes.  We mostly want to use the Pangeo-binder just to expose more people to it and highlight it's existence to new communities.

**Comment by rabernat** [comment]
I appreciate your desire to promote Pangeo! In this case, our binder is not providing any special functionality beyond standard binder. (In fact, it is providing less, since it's broken!) If you want to highlight Pangeo, you can emphasize
- the software (e.g. xarray) on which your demo depends was supported by pangeo
- the community, which is helping raise awareness about reproducibility and cloud computing tools like binder

We'll try to get this fixed, but I wouldn't count on it for tomorrow.

**Comment by cgentemann** [comment]
Okay! We have the mybinder image on the repository as well, so we are good to go and will highlight Pangeo in the ways you recommend. Once fixed, we will just remove the mybinder image. Thanks!

**Comment by rabernat** [comment]
This is still an annoying problem. Any ideas how to fix?

**Comment by cgentemann** [comment]
Figured out a fix from here: https://github.com/jupyterlab/jupyterlab/issues/6149 
In your environment.yml file, add 
  - notebook=5.7.5
I tested using: binder button here: https://github.com/python4oceanography/PICES-tools
Sorry it took so long.  Chelle

**Comment by rabernat** [comment]
Amazing, thanks @cgentemann!

I also noticed that it works in Safari browser without any modification.
