### ISSUE TITLE
Problem when creating cluster: "suggest closing worker"

### ISSUE THREAD

**Issue by lwchao-vivian** [pangeo-data/pangeo-binder#83]
Hi everyone,

I created my own repository and run it on binder.pangeo.io:
[https://binder.pangeo.io/v2/gh/lwchao-vivian/Pangeo_cluster/master](https://binder.pangeo.io/v2/gh/lwchao-vivian/Pangeo_cluster/master)

However, when I tried to create a Desk cluster in Pangeo_calculate_ECS_and_feedback.ipynb, it kept showing the warning messages that asked me to close the workers. The error message is like:
distributed.scheduler - INFO - Suggest closing workers

This error message didn't show up when I run hello_world.ipynb. Does anyone know how to solve this issue? Thank you.

**Comment by TomAugspurger** [comment]
Hi  @lwchao-vivian. Those are log messages that can be ignored. Typically they're hidden, but something changed in Dask recently, so they're showing up in the notebook. This is being fixed in https://github.com/pangeo-data/pangeo-stacks/pull/92

**Comment by lwchao-vivian** [comment]
@TomAugspurger Thank you for your response! In my case, after all of the "Suggest closing workers" messages, Dask removed the workers and I lost all of them. Do you know how to fix it?

**Comment by TomAugspurger** [comment]
Loading your binder now. It's rebuilding the image so it may be a bit.

Are you using adaptive? That could just be Dask saying that the cluster is idle, so it's releasing all the workers.

**Comment by lwchao-vivian** [comment]
Yes, I am using adapt. 
It would be nice if there is a way to hide these messages. Can you elaborate what your meaning of "specify logging at the top-level" in [pangeo-data/pangeo-stacks#92](https://github.com/pangeo-data/pangeo-stacks/pull/92)?

**Comment by lwchao-vivian** [comment]
I noticed that the problem of looping messages can be avoided by specifying the number of workers:
That is, 
`cluster = KubeCluster()`
`cluster.adapt(minimum=4, maximum=40)`
should be replaced with
`cluster = KubeCluster(n_workers=4)`

Thank you for your assistance!

**Comment by mrocklin** [comment]
These are actually logged at debug level today in Dask.  Pangeo should probably change their base image to point to `dask >= 2.7`.

**Comment by TomAugspurger** [comment]
https://github.com/pangeo-data/pangeo-stacks/pull/92 is updating the dask_config.yaml that's used in the base image. On master, the logging configuration is under the "distributed" key in the YAML file, but it shouldn't be.

And just to be clear, you may want to continue using `adapt`. This problem will solve itself once https://github.com/pangeo-data/pangeo-stacks/pull/92/files is merged and the docker images are rebuilt (probably toay or tomrrow).

**Comment by lwchao-vivian** [comment]
That's clear. Now I understand. Thank you @mrocklin and @TomAugspurger !
