### ISSUE TITLE
add pangeo branding to binder.pangeo.io

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-binder#9]
Currently, the main binderhub page on binder.pangeo.io looks a lot like mybinder.org. You actually have to read the text to see that there are some differences. It would be great to update the layout of the page to highlight the difference and to give pangeo a bigger presence. Visual/web design is not really a skill set I have so any help/ideas from others would be appreciated here.

This repo is where we can override style things: https://github.com/pangeo-data/pangeo-custom-binderhub-templates

**Comment by niallrobinson** [comment]
calling @meganfitzsimons

**Comment by jhamman** [comment]
Thanks, this looks much better :)

Thoughts on including the binder logo too?

![pangeo binder](https://user-images.githubusercontent.com/2443309/45110553-78820e00-b0f7-11e8-82cc-8e447d1a02d1.png)

A few references (you may already know where these are):
- pangeo's branding repo (including fonts, colors, etc): https://github.com/pangeo-data/branding
- pangeo's website css (including fonts, colors, etc): https://github.com/pangeo-data/pangeo/blob/master/docs/_static/pangeo-style.css

Last thing, can we add these little blurbs at the bottom of the page:

> [Pangeo](pangeo.io) is a community effort for big data geoscience. This [BinderHub](https://binderhub.readthedocs.io) is a multi-user server for interactive data analysis running on [Google Cloud Platform](https://cloud.google.com/). 
> 
> Acknowledgments: Pangeo is supported, in part, by the [National Science Foundation (NSF)](https://www.nsf.gov/) and the [National Aeronautics and Space Administration (NASA)](https://www.nasa.gov/). Google provided compute credits on Google Compute Engine.

**Comment by dsludwig** [comment]
I think that's a good idea. I've created a pull request against the theme repository here: https://github.com/pangeo-data/pangeo-custom-binderhub-templates/pull/1

**Comment by jhamman** [comment]
keeping open for discussion.

**Comment by rabernat** [comment]
Looks awesome!

**Comment by rabernat** [comment]
To the acknowledgements, I would make sure to give due credit to the binder / jupyter team.
