### ISSUE TITLE
Image renewal

### ISSUE THREAD

**Issue by gmaze** [pangeo-data/pangeo-binder#90]
Hi,
I love to work with the binder.pangeo.io on my teaching repo:
https://github.com/obidam/m2poc2018
https://github.com/obidam/m2poc2019
https://github.com/obidam/pyxpcm-examples

However, when I update frequently my repo with new notebooks (or binder settings) during my class preparation, I noticed that the cached image is taking over and I don't see the updates.

So my questions are:
- how long an image is cached ?
- is there a mechanism to force image building (for the dev time, not use) ?

Thanks for your answer !
gm

**Comment by scottyhq** [comment]
pangeo binder works just like mybinder.org, so every commit to the binder configuration repo forces a rebuild. We might purge the repository of built imagers from time to time as well. See this post for helpful guidance on decoupling the binder infrastructure configuration from content (e.g. notebooks): https://discourse.jupyter.org/t/tip-embed-custom-github-content-in-a-binder-link-with-nbgitpuller/922

**Comment by TomAugspurger** [comment]
I think everything here has been answered.
